version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: registry.web.boeing.com/angel.d.avila/osee-docker
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    ports:
        - "8900:20152"
    networks:
      - webnet
networks:
  webnet:
